# Generated by Django 5.2.7 on 2025-10-21 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_article", "0013_delete_articlereviewmodel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleReviewModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Comentario")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="app_article.articlemodel",
                        verbose_name="Artículo",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="article_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Revisor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Revisión",
                "verbose_name_plural": "Revisiones",
                "ordering": ["-created_at"],
            },
        ),
    ]
