# Generated by Django 5.2.7 on 2025-10-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_article", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlemodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Borrador"),
                    ("published", "Publicado"),
                    ("pending", "En revisión"),
                ],
                default="draft",
                verbose_name="Estado",
            ),
        ),
    ]
