# Generated by Django 5.2.7 on 2025-10-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_article", "0004_alter_articlemodel_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlemodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En revisión"),
                    ("published", "Publicado"),
                    ("draft", "Borrador"),
                ],
                default="draft",
                verbose_name="Estado",
            ),
        ),
    ]
