# Generated by Django 5.2.7 on 2025-10-17 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_article", "0008_alter_articlemodel_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlereviewmodel",
            name="approved",
        ),
    ]
