# Generated by Django 5.2.7 on 2025-10-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_article", "0009_remove_articlereviewmodel_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlemodel",
            name="category",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Categoría"
            ),
        ),
        migrations.AddField(
            model_name="articlemodel",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="articles/covers/",
                verbose_name="Imagen de portada",
            ),
        ),
    ]
