# Generated by Django 5.2.7 on 2025-10-19 20:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_article", "0010_articlemodel_category_articlemodel_cover_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="articlemodel",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_articles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Me gusta",
            ),
        ),
    ]
