# Generated by Django 5.2.7 on 2025-10-21 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_article", "0012_articlecommentmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ArticleReviewModel",
        ),
    ]
